blank_issues_enabled: false

contact_links:
  - name: ❓ Start a discussion or ask a question about Cycle ORM.
    url: https://github.com/cycle/orm/discussions
    about: Please ask and answer questions here.
